global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'ng-activity-backend'
    static_configs:
      - targets: ['localhost:3100']
    metrics_path: '/metrics'
    scrape_interval: 5s